name: dep-pkg CI

on:
  pull_request:
    paths:
      - dep-pkg/**
      - .github/workflows/ci-dep-pkg.yml
    branches:
      - master

jobs:
  lint-python:
    uses: ./.github/workflows/lint-python.yml
    with:
      python-version: 3.11

  test-python:
    uses: ./.github/workflows/test-python.yml
    with:
      python-version: 3.11
      package: "dep-pkg"
