name: Lint Python
on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.11
          architecture: x64
          prerelease: false
          enable-pep582: true
          cache: true
          cache-dependency-path: './pdm.lock'
      - name: Install dependencies
        run: pdm sync -v -G lint

      - name: Check ruff
        run: pdm run -v ruff check . --format=github
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.11
          architecture: x64
          prerelease: false
          enable-pep582: true
          cache: true
          cache-dependency-path: './pdm.lock'
      - name: Install dependencies
        run: pdm sync -v -G lint

      - name: Check black
        run: pdm run -v black --check .
