name: Test Runner

on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup override set stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Test Rust
        run: cargo test
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Create virtual environment
        run: |
          python -m venv .pyenv
          echo "$GITHUB_WORKSPACE/.pyenv/bin" >> $GITHUB_PATH

      - name: Build Python wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out=build
      - name: Install Python wheel
        run: pip install build/*.whl
      - name: Install pytest
        run: pip install pytest pytest-xdist
      - name: Test Python
        run: pytest -n auto
