name: Test Runner

on: workflow_dispatch

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup override set stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        working-directory: examples
        run: cargo check
