name: Run Nextest

on: workflow_call

# https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: rustup show
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Test Rust
        run: cargo test --locked --all-features --all-targets
      - name: Test Rust Docs
        run: cargo test --locked --all-features --doc
