name: Test Python

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: rustup show
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.11
          architecture: x64
          prerelease: false
          enable-pep582: true
          cache: true
          cache-dependency-path: './pdm.lock'
      - name: Install dependencies
        run: pdm sync -v -G dev -G test
      - name: Test Python
        run: pdm run -v pytest -n auto
